version: "3.9"

services:

  web:
    build:
      context: .

    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: config

    volumes:
      - .:/config
    ports:
      - "8000:8000"
