# Generated by Django 4.2.11 on 2024-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Nomi:')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Foydalanuvchi_',
            },
        ),
    ]
