# Generated by Django 4.1.4 on 2025-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
