name: Django CI/CD

on:
  push:
    branches: [ "main" ]  # Main branchga push qilinsa ishga tushadi

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations check
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Project papkasiga o‘tish
            cd /root/Mahon.uz
            
            # GitHub dan oxirgi kodni olish
            git fetch --all
            git reset --hard origin/main
            
            # Virtual environment faollashtirish
            source /root/Mahon.uz/venv/bin/activate
            
            # Paketlarni yangilash
            pip install --upgrade -r requirements.txt
            
            # Django migrate va static fayllar
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            
            # Serverni restart qilish
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
